from typing import Protocol, Iterable
from .models import Device

class DeviceRepository(Protocol):
    def list(self) -> list[Device]: ...
    def get(self, id: int) -> Device | None: ...
    def upsert(self, device: Device) -> Device: ...
    def delete(self, id: int) -> Device | None: ...

class EventPublisher(Protocol):
    async def publish(self, event: dict) -> None: ...
